# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 💥 Breaking changes
    when:
      labels:
        - breaking
  - title: 🚨 Removed
    when:
      labels:
        - removed
  - title: 🎉 Major features and improvements
    when:
      labels:
        - major-enhancement
        - major-rfe
  - title: 🐛 Major bug fixes
    when:
      labels:
        - major-bug
  - title: ⚠️ Deprecated
    when:
      labels:
        - deprecated
  - title: 🚀 New features and improvements
    when:
      labels:
        - enhancement
        - feature
  - title: 🐛 Bug fixes
    when:
      labels:
        - bug
        - fix
        - bugfix
        - regression
  - title: 🌐 Localization and translation
    when:
      labels:
        - localization
  - title: 👷 Changes for developers
    when:
      labels:
        - developer
  - title: 📝 Documentation updates
    when:
      labels:
        - documentation
  - title: 👻 Maintenance
    when:
      labels:
        - chore
        - internal
        - maintenance
  - title: 🚦 Tests
    when:
      labels:
        - test
        - tests
  - title: ✍ Other changes
  - title: 📦 Dependency updates
    when:
      labels:
        - dependencies
    collapse-after: 15
  - type: pre-exclude
    when:
      labels:
        - no-changelog
        - skip-changelog
        - invalid
  - type: version-resolver
    semver-increment: major
    when:
      labels:
        - major
  - type: version-resolver
    semver-increment: minor
    when:
      labels:
        - minor
  - type: version-resolver
    semver-increment: patch
    when:
      labels:
        - patch
  - type: version-resolver
    semver-increment: patch

change-template: '- $TITLE by @$AUTHOR in #$NUMBER'

template: |
  <!-- Optional: add a release summary here -->
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
