name: MkDocs Deploy

on:
  workflow_call:

jobs:
  mkdocs-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r docs/requirements.txt
      - name: check mkdocs build
        if: github.ref != 'refs/heads/main'
        run: mkdocs build
      - name: Upload docs build as artifact
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ github.event.repository.name }}_docs
          path: ${{ github.workspace }}/site
      - name: Build docs and deploy to gh-pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name 'github-actions'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          mkdocs gh-deploy --force
