name: PR Labeler

on:
  workflow_call:

jobs:
  label_pr:
    permissions:
      # write permission is required for autolabeler
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      # Automatically label pull requests based on the release-drafter config
      - uses: release-drafter/release-drafter/autolabeler@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: github:shenxianpeng/.github:/.github/release-drafter.yml
