name: PR Labeler

on:
  workflow_call:

jobs:
  label_pr:
    permissions:
      # write permission is required for autolabeler
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      # Automatically label pull requests based on the release-drafter config
      - uses: release-drafter/release-drafter/autolabeler@693d20e7c1ce1a81d3a41962f85914253b518449 # v7.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: github:shenxianpeng/.github:/.github/release-drafter.yml
