name: PR Labeler

on:
  workflow_call:

jobs:
  label_pr:
    permissions:
      # write permission is required for autolabeler
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      # Automatically label pull requests based on the release-drafter config
      - uses: release-drafter/release-drafter/autolabeler@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: github:shenxianpeng/.github:/.github/release-drafter.yml
